name: jHDF Release

on:
    # When a release is created
    release:
        types: [created]
    # Manual
    workflow_dispatch:

jobs:
    release:
        # Access environment with release keys
        environment: release

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK
                uses: actions/setup-java@v2
                with:
                    # Must use lowest supported Java version
                    java-version: '8'
                    distribution: 'adopt'

            - name: Build
                working-directory: jhdf
                run: ./gradlew assemble

            -   name: Test
                    working-directory: jhdf
                    run: ./gradlew check

            - name: Gradle Build Jars
                working-directory: jhdf
                run: ./gradlew jar sourcesJar javadocJar

            - name: Sign Publication
                working-directory: jhdf
                run: ./gradlew signMavenPublication
