name: 'jHDF Release'

on:
    # When a release is created
    release:
        types:
            - created
    pull_request:
        branches: [ master ]

    # Manual
    workflow_dispatch:

jobs:
    release:
        name: "Publish Release"
        runs-on: ubuntu-latest
        # Access environment with release keys
        environment: Release

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  # Must use lowest supported Java version
                  java-version: '8'
                  distribution: 'adopt'

#            - name: Test Env
#              env:
#                  TEST_SECRET: ${{ secrets.TEST_SECRET }}
#              run: echo $TEST_SECRET; echo "hello"

            - name: Build
              working-directory: jhdf
              run: ./gradlew assemble

            - name: Test
              working-directory: jhdf
              run: ./gradlew check

            - name: Gradle Build Jars
              working-directory: jhdf
              run: ./gradlew jar sourcesJar javadocJar

            - name: Sign Publication
              env:
                  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
              working-directory: jhdf
              run: ./gradlew signMavenPublication -PsigningKey="$SIGNING_KEY" -PsigningPassword="$SIGNING_PASSWORD"

            - name: Archive Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: artifacts
                  path: |
                    jhdf/build/libs
                    jhdf/build/publications

            - name: Publish to GitHub Packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: ./gradlew
