name: 'jHDF Release'

on:
    # When a release is created
    release:
        types:
            - created
    pull_request:
        branches: [ master ]

    # Manual
    #workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        # Access environment with release keys
        environment: Release

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  # Must use lowest supported Java version
                  java-version: '8'
                  distribution: 'adopt'

            - name: Test Env
              run: echo $TEST_SECRET

#            - name: Build
#              working-directory: jhdf
#              run: ./gradlew assemble
#
#            - name: Test
#              working-directory: jhdf
#              run: ./gradlew check
#
#            - name: Gradle Build Jars
#              working-directory: jhdf
#              run: ./gradlew jar sourcesJar javadocJar
#
#            - name: Sign Publication
#              working-directory: jhdf
#              run: ./gradlew signMavenPublication
